<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <!-- BEGIN PAGE HEAD-->
        <div class="page-head">
            <!-- BEGIN PAGE TITLE -->
            <div class="page-title">
                <h1>Dashboard
                    <small>dashboard & statistics</small>
                </h1>
            </div>
            <!-- END PAGE TITLE -->
            <!-- BEGIN PAGE TOOLBAR -->
            <div class="page-toolbar">
                <div id="dashboard-report-range" class="pull-right tooltips btn btn-fit-height green" data-placement="top" data-original-title="Change dashboard date range">
                    <i class="icon-calendar"></i>&nbsp;
                    <span class="thin uppercase hidden-xs"></span>&nbsp;
                    <i class="fa fa-angle-down"></i>
                </div>
                <!-- BEGIN THEME PANEL -->
                <div class="btn-group btn-theme-panel">
                    <a href="javascript:;" class="btn dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-settings"></i>
                    </a>
                    <div class="dropdown-menu theme-panel pull-right dropdown-custom hold-on-click">
                        <div class="row">
                            <div class="col-md-4 col-sm-4 col-xs-12">
                                <h3>THEME</h3>
                                <ul class="theme-colors">
                                    <li class="theme-color theme-color-default" data-theme="default">
                                        <span class="theme-color-view"></span>
                                        <span class="theme-color-name">Dark Header</span>
                                    </li>
                                    <li class="theme-color theme-color-light active" data-theme="light">
                                        <span class="theme-color-view"></span>
                                        <span class="theme-color-name">Light Header</span>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-8 col-sm-8 col-xs-12 seperator">
                                <h3>LAYOUT</h3>
                                <ul class="theme-settings">
                                    <li> Theme Style
                                        <select class="layout-style-option form-control input-small input-sm">
                                            <option value="square">Square corners</option>
                                            <option value="rounded" selected="selected">Rounded corners</option>
                                        </select>
                                    </li>
                                    <li> Layout
                                        <select class="layout-option form-control input-small input-sm">
                                            <option value="fluid" selected="selected">Fluid</option>
                                            <option value="boxed">Boxed</option>
                                        </select>
                                    </li>
                                    <li> Header
                                        <select class="page-header-option form-control input-small input-sm">
                                            <option value="fixed" selected="selected">Fixed</option>
                                            <option value="default">Default</option>
                                        </select>
                                    </li>
                                    <li> Top Dropdowns
                                        <select class="page-header-top-dropdown-style-option form-control input-small input-sm">
                                            <option value="light">Light</option>
                                            <option value="dark" selected="selected">Dark</option>
                                        </select>
                                    </li>
                                    <li> Sidebar Mode
                                        <select class="sidebar-option form-control input-small input-sm">
                                            <option value="fixed">Fixed</option>
                                            <option value="default" selected="selected">Default</option>
                                        </select>
                                    </li>
                                    <li> Sidebar Menu
                                        <select class="sidebar-menu-option form-control input-small input-sm">
                                            <option value="accordion" selected="selected">Accordion</option>
                                            <option value="hover">Hover</option>
                                        </select>
                                    </li>
                                    <li> Sidebar Position
                                        <select class="sidebar-pos-option form-control input-small input-sm">
                                            <option value="left" selected="selected">Left</option>
                                            <option value="right">Right</option>
                                        </select>
                                    </li>
                                    <li> Footer
                                        <select class="page-footer-option form-control input-small input-sm">
                                            <option value="fixed">Fixed</option>
                                            <option value="default" selected="selected">Default</option>
                                        </select>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- END THEME PANEL -->
            </div>
            <!-- END PAGE TOOLBAR -->
        </div>
        <!-- END PAGE HEAD-->
        <!-- BEGIN PAGE BREADCRUMB -->
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <a href="index.html">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span class="active">Dashboard</span>
            </li>
        </ul>
        <!-- END PAGE BREADCRUMB -->
        <!-- BEGIN PAGE BASE CONTENT -->
        <!-- BEGIN DASHBOARD STATS 1-->
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <a class="dashboard-stat dashboard-stat-v2 blue" href="#">
                    <div class="visual">
                        <i class="fa fa-comments"></i>
                    </div>
                    <div class="details">
                        <div class="number">
                            <span data-counter="counterup" data-value="1349">0</span>
                        </div>
                        <div class="desc"> New Feedbacks </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <a class="dashboard-stat dashboard-stat-v2 red" href="#">
                    <div class="visual">
                        <i class="fa fa-bar-chart-o"></i>
                    </div>
                    <div class="details">
                        <div class="number">
                            <span data-counter="counterup" data-value="12,5">0</span>M$ </div>
                        <div class="desc"> Total Profit </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <a class="dashboard-stat dashboard-stat-v2 green" href="#">
                    <div class="visual">
                        <i class="fa fa-shopping-cart"></i>
                    </div>
                    <div class="details">
                        <div class="number">
                            <span data-counter="counterup" data-value="549">0</span>
                        </div>
                        <div class="desc"> New Orders </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <a class="dashboard-stat dashboard-stat-v2 purple" href="#">
                    <div class="visual">
                        <i class="fa fa-globe"></i>
                    </div>
                    <div class="details">
                        <div class="number"> +
                            <span data-counter="counterup" data-value="89"></span>% </div>
                        <div class="desc"> Brand Popularity </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="clearfix"></div>
        <!-- END DASHBOARD STATS 1-->
        <div class="row">
            <div class="col-md-6 col-sm-6">
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <div class="portlet light portlet-fit bordered">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-directions font-green hide"></i>
                            <span class="caption-subject bold font-dark uppercase "> Activities</span>
                            <span class="caption-helper">Horizontal Timeline</span>
                        </div>
                        <div class="actions">
                            <div class="btn-group">
                                <a class="btn blue btn-outline btn-circle btn-sm" href="javascript:;" data-toggle="dropdown" data-hover="dropdown" data-close-others="true"> Actions
                                    <i class="fa fa-angle-down"></i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li>
                                        <a href="javascript:;"> Action 1</a>
                                    </li>
                                    <li class="divider"> </li>
                                    <li>
                                        <a href="javascript:;">Action 2</a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">Action 3</a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">Action 4</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="cd-horizontal-timeline mt-timeline-horizontal">
                            <div class="timeline">
                                <div class="events-wrapper">
                                    <div class="events">
                                        <ol>
                                            <li>
                                                <a href="#0" data-date="16/01/2014" class="border-after-red bg-after-red selected">16 Jan</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="28/02/2014" class="border-after-red bg-after-red">28 Feb</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="20/04/2014" class="border-after-red bg-after-red">20 Mar</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="20/05/2014" class="border-after-red bg-after-red">20 May</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="09/07/2014" class="border-after-red bg-after-red">09 Jul</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="30/08/2014" class="border-after-red bg-after-red">30 Aug</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="15/09/2014" class="border-after-red bg-after-red">15 Sep</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="01/11/2014" class="border-after-red bg-after-red">01 Nov</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="10/12/2014" class="border-after-red bg-after-red">10 Dec</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="19/01/2015" class="border-after-red bg-after-red">29 Jan</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="03/03/2015" class="border-after-red bg-after-red">3 Mar</a>
                                            </li>
                                        </ol>
                                        <span class="filling-line bg-red" aria-hidden="true"></span>
                                    </div>
                                    <!-- .events -->
                                </div>
                                <!-- .events-wrapper -->
                                <ul class="cd-timeline-navigation mt-ht-nav-icon">
                                    <li>
                                        <a href="#0" class="prev inactive btn btn-outline red md-skip">
                                            <i class="fa fa-chevron-left"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#0" class="next btn btn-outline red md-skip">
                                            <i class="fa fa-chevron-right"></i>
                                        </a>
                                    </li>
                                </ul>
                                <!-- .cd-timeline-navigation -->
                            </div>
                            <!-- .timeline -->
                            <div class="events-content">
                                <ol>
                                    <li class="selected" data-date="16/01/2014">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">New User</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_3.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Andres Iniesta</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">16 January 2014 : 7:45 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod eleifend ipsum, at posuere augue. Pellentesque mi felis, aliquam at iaculis eu, mi felis, aliquam at iaculis mi felis, aliquam
                                                at iaculis finibus eu ex. Integer efficitur tincidunt malesuada. Sed sit amet molestie elit, vel placerat ipsum. Ut consectetur odio non est rhoncus volutpat.</p>
                                            <a href="javascript:;" class="btn btn-circle red btn-outline">Read More</a>
                                            <a href="javascript:;" class="btn btn-circle btn-icon-only blue">
                                                <i class="fa fa-plus"></i>
                                            </a>
                                            <a href="javascript:;" class="btn btn-circle btn-icon-only green pull-right">
                                                <i class="fa fa-twitter"></i>
                                            </a>
                                        </div>
                                    </li>
                                    <li data-date="28/02/2014">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Sending Shipment</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_3.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Hugh Grant</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">28 February 2014 : 10:15 AM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod eleifend ipsum, at posuere augue. Pellentesque mi felis, aliquam at iaculis eu, finibus eu ex. Integer efficitur leo eget dolor
                                                tincidunt, et dignissim risus lacinia. Nam in egestas nunc. Suspendisse potenti. Cras ullamcorper tincidunt malesuada. Sed sit amet molestie elit, vel placerat ipsum. Ut consectetur odio non
                                                est rhoncus volutpat. Nullam interdum, neque quis vehicula ornare, lacus elit dignissim purus, quis ultrices erat tortor eget felis. Cras commodo id massa at condimentum. Praesent dignissim luctus
                                                risus sed sodales.</p>
                                            <a href="javascript:;" class="btn btn-circle btn-outline green-jungle">Download Shipment List</a>
                                            <div class="btn-group dropup pull-right">
                                                <button class="btn btn-circle blue-steel dropdown-toggle" type="button" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" aria-expanded="false"> Actions
                                                    <i class="fa fa-angle-down"></i>
                                                </button>
                                                <ul class="dropdown-menu pull-right" role="menu">
                                                    <li>
                                                        <a href="javascript:;">Action </a>
                                                    </li>
                                                    <li>
                                                        <a href="javascript:;">Another action </a>
                                                    </li>
                                                    <li>
                                                        <a href="javascript:;">Something else here </a>
                                                    </li>
                                                    <li class="divider"> </li>
                                                    <li>
                                                        <a href="javascript:;">Separated link </a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                    <li data-date="20/04/2014">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Blue Chambray</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_1.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue">Rory Matthew</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">20 April 2014 : 10:45 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod eleifend ipsum, at posuere augue. Pellentesque mi felis, aliquam at iaculis eu, finibus eu ex. Integer efficitur leo eget dolor
                                                tincidunt, et dignissim risus lacinia. Nam in egestas nunc. Suspendisse potenti. Cras ullamcorper tincidunt malesuada. Sed sit amet molestie elit, vel placerat ipsum. Ut consectetur odio non
                                                est rhoncus volutpat. Nullam interdum, neque quis vehicula ornare, lacus elit dignissim purus, quis ultrices erat tortor eget felis. Cras commodo id massa at condimentum. Praesent dignissim luctus
                                                risus sed sodales.</p>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis
                                                qui ut. laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut. </p>
                                            <a href="javascript:;" class="btn btn-circle red">Read More</a>
                                        </div>
                                    </li>
                                    <li data-date="20/05/2014">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Timeline Received</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_2.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Andres Iniesta</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">20 May 2014 : 12:20 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod eleifend ipsum, at posuere augue. Pellentesque mi felis, aliquam at iaculis eu, finibus eu ex. Integer efficitur leo eget dolor
                                                tincidunt, et dignissim risus lacinia. Nam in egestas nunc. Suspendisse potenti. Cras ullamcorper tincidunt malesuada. Sed sit amet molestie elit, vel placerat ipsum. Ut consectetur odio non
                                                est rhoncus volutpat. Nullam interdum, neque quis vehicula ornare, lacus elit dignissim purus, quis ultrices erat tortor eget felis. Cras commodo id massa at condimentum. Praesent dignissim luctus
                                                risus sed sodales.</p>
                                            <a href="javascript:;" class="btn btn-circle green-turquoise">Read More</a>
                                        </div>
                                    </li>
                                    <li data-date="09/07/2014">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Event Success</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_1.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Matt Goldman</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">9 July 2014 : 8:15 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde.</p>
                                            <a href="javascript:;" class="btn btn-circle btn-outline purple-medium">View Summary</a>
                                            <div class="btn-group dropup pull-right">
                                                <button class="btn btn-circle green dropdown-toggle" type="button" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" aria-expanded="false"> Actions
                                                    <i class="fa fa-angle-down"></i>
                                                </button>
                                                <ul class="dropdown-menu pull-right" role="menu">
                                                    <li>
                                                        <a href="javascript:;">Action </a>
                                                    </li>
                                                    <li>
                                                        <a href="javascript:;">Another action </a>
                                                    </li>
                                                    <li>
                                                        <a href="javascript:;">Something else here </a>
                                                    </li>
                                                    <li class="divider"> </li>
                                                    <li>
                                                        <a href="javascript:;">Separated link </a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                    <li data-date="30/08/2014">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Conference Call</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_1.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Rory Matthew</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">30 August 2014 : 5:45 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <img class="timeline-body-img pull-left" src="../assets/pages/media/blog/5.jpg" alt="">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis
                                                qui ut. laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut. </p>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis
                                                qui ut. laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut. </p>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis
                                                qui ut. laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut. </p>
                                            <a href="javascript:;" class="btn btn-circle red">Read More</a>
                                        </div>
                                    </li>
                                    <li data-date="15/09/2014">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Conference Decision</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_5.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Jessica Wolf</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">15 September 2014 : 8:30 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <img class="timeline-body-img pull-right" src="../assets/pages/media/blog/6.jpg" alt="">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis
                                                qui ut.</p>
                                            <a href="javascript:;" class="btn btn-circle green-sharp">Read More</a>
                                        </div>
                                    </li>
                                    <li data-date="01/11/2014">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Timeline Received</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_2.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Andres Iniesta</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">1 November 2014 : 12:20 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod eleifend ipsum, at posuere augue. Pellentesque mi felis, aliquam at iaculis eu, finibus eu ex. Integer efficitur leo eget dolor
                                                tincidunt, et dignissim risus lacinia. Nam in egestas nunc. Suspendisse potenti. Cras ullamcorper tincidunt malesuada. Sed sit amet molestie elit, vel placerat ipsum. Ut consectetur odio non
                                                est rhoncus volutpat. Nullam interdum, neque quis vehicula ornare, lacus elit dignissim purus, quis ultrices erat tortor eget felis. Cras commodo id massa at condimentum. Praesent dignissim luctus
                                                risus sed sodales.</p>
                                            <a href="javascript:;" class="btn btn-circle green-turquoise">Read More</a>
                                        </div>
                                    </li>
                                    <li data-date="10/12/2014">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Timeline Received</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_2.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Andres Iniesta</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">10 December 2015 : 12:20 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod eleifend ipsum, at posuere augue. Pellentesque mi felis, aliquam at iaculis eu, finibus eu ex. Integer efficitur leo eget dolor
                                                tincidunt, et dignissim risus lacinia. Nam in egestas nunc. Suspendisse potenti. Cras ullamcorper tincidunt malesuada. Sed sit amet molestie elit, vel placerat ipsum. Ut consectetur odio non
                                                est rhoncus volutpat. Nullam interdum, neque quis vehicula ornare, lacus elit dignissim purus, quis ultrices erat tortor eget felis. Cras commodo id massa at condimentum. Praesent dignissim luctus
                                                risus sed sodales.</p>
                                            <a href="javascript:;" class="btn btn-circle green-turquoise">Read More</a>
                                        </div>
                                    </li>
                                    <li data-date="19/01/2015">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Timeline Received</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_2.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Andres Iniesta</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">19 January 2015 : 12:20 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod eleifend ipsum, at posuere augue. Pellentesque mi felis, aliquam at iaculis eu, finibus eu ex. Integer efficitur leo eget dolor
                                                tincidunt, et dignissim risus lacinia. Nam in egestas nunc. Suspendisse potenti. Cras ullamcorper tincidunt malesuada. Sed sit amet molestie elit, vel placerat ipsum. Ut consectetur odio non
                                                est rhoncus volutpat. Nullam interdum, neque quis vehicula ornare, lacus elit dignissim purus, quis ultrices erat tortor eget felis. Cras commodo id massa at condimentum. Praesent dignissim luctus
                                                risus sed sodales.</p>
                                            <a href="javascript:;" class="btn btn-circle green-turquoise">Read More</a>
                                        </div>
                                    </li>
                                    <li data-date="03/03/2015">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Timeline Received</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_2.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Andres Iniesta</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">3 March 2015 : 12:20 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod eleifend ipsum, at posuere augue. Pellentesque mi felis, aliquam at iaculis eu, finibus eu ex. Integer efficitur leo eget dolor
                                                tincidunt, et dignissim risus lacinia. Nam in egestas nunc. Suspendisse potenti. Cras ullamcorper tincidunt malesuada. Sed sit amet molestie elit, vel placerat ipsum. Ut consectetur odio non
                                                est rhoncus volutpat. Nullam interdum, neque quis vehicula ornare, lacus elit dignissim purus, quis ultrices erat tortor eget felis. Cras commodo id massa at condimentum. Praesent dignissim luctus
                                                risus sed sodales.</p>
                                            <a href="javascript:;" class="btn btn-circle green-turquoise">Read More</a>
                                        </div>
                                    </li>
                                </ol>
                            </div>
                            <!-- .events-content -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-6">
                <div class="portlet light portlet-fit bordered">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-directions font-green hide"></i>
                            <span class="caption-subject bold font-dark uppercase"> Events</span>
                            <span class="caption-helper">Horizontal Timeline</span>
                        </div>
                        <div class="actions">
                            <div class="btn-group btn-group-devided" data-toggle="buttons">
                                <label class="btn green btn-outline btn-circle btn-sm active">
                                    <input type="radio" name="options" class="toggle" id="option1">Actions</label>
                                <label class="btn  green btn-outline btn-circle btn-sm">
                                    <input type="radio" name="options" class="toggle" id="option2">Tools</label>
                            </div>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="cd-horizontal-timeline mt-timeline-horizontal">
                            <div class="timeline mt-timeline-square">
                                <div class="events-wrapper">
                                    <div class="events">
                                        <ol>
                                            <li>
                                                <a href="#0" data-date="16/01/2014" class="border-after-blue bg-after-blue selected">Expo 2016</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="28/02/2014" class="border-after-blue bg-after-blue">New Promo</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="20/04/2014" class="border-after-blue bg-after-blue">Meeting</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="20/05/2014" class="border-after-blue bg-after-blue">Launch</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="09/07/2014" class="border-after-blue bg-after-blue">Party</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="30/08/2014" class="border-after-blue bg-after-blue">Reports</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="15/09/2014" class="border-after-blue bg-after-blue">HR</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="01/11/2014" class="border-after-blue bg-after-blue">IPO</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="10/12/2014" class="border-after-blue bg-after-blue">Board</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="19/01/2015" class="border-after-blue bg-after-blue">Revenue</a>
                                            </li>
                                            <li>
                                                <a href="#0" data-date="03/03/2015" class="border-after-blue bg-after-blue">Dinner</a>
                                            </li>
                                        </ol>
                                        <span class="filling-line bg-blue" aria-hidden="true"></span>
                                    </div>
                                    <!-- .events -->
                                </div>
                                <!-- .events-wrapper -->
                                <ul class="cd-timeline-navigation mt-ht-nav-icon">
                                    <li>
                                        <a href="#0" class="prev inactive btn blue md-skip">
                                            <i class="fa fa-chevron-left"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#0" class="next btn blue md-skip">
                                            <i class="fa fa-chevron-right"></i>
                                        </a>
                                    </li>
                                </ul>
                                <!-- .cd-timeline-navigation -->
                            </div>
                            <!-- .timeline -->
                            <div class="events-content">
                                <ol>
                                    <li class="selected" data-date="16/01/2014">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Expo 2016 Launch</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_2.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Lisa Bold</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">23 February 2014</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod mi felis, aliquam at iaculis eleifend ipsum, at posuere augue. Pellentesque mi felis, aliquam at iaculis mi felis, aliquam at
                                                iaculis eu, onsectetur adipiscing elit finibus eu ex. Integer efficitur leo eget dolor tincidunt, et dignissim risus lacinia. Nam in egestas onsectetur adipiscing elit nunc. Suspendisse potenti</p>
                                            <a href="javascript:;" class="btn btn-circle dark btn-outline">Read More</a>
                                            <a href="javascript:;" class="btn btn-circle btn-icon-only green pull-right">
                                                <i class="fa fa-twitter"></i>
                                            </a>
                                        </div>
                                    </li>
                                    <li data-date="28/02/2014">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Sending Shipment</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_3.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Hugh Grant</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">28 February 2014 : 10:15 AM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod eleifend ipsum, at posuere augue. Pellentesque mi felis, aliquam at iaculis eu, finibus eu ex. Integer efficitur leo eget dolor
                                                tincidunt, et dignissim risus lacinia. Nam in egestas nunc. Suspendisse potenti. Cras ullamcorper tincidunt malesuada. Sed sit amet molestie elit, vel placerat ipsum. Ut consectetur odio non
                                                est rhoncus volutpat. Nullam interdum, neque quis vehicula ornare, lacus elit dignissim purus, quis ultrices erat tortor eget felis. Cras commodo id massa at condimentum. Praesent dignissim luctus
                                                risus sed sodales.</p>
                                            <a href="javascript:;" class="btn btn-circle btn-outline green-jungle">Download Shipment List</a>
                                            <div class="btn-group dropup pull-right">
                                                <button class="btn btn-circle blue-steel dropdown-toggle" type="button" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" aria-expanded="false"> Actions
                                                    <i class="fa fa-angle-down"></i>
                                                </button>
                                                <ul class="dropdown-menu pull-right" role="menu">
                                                    <li>
                                                        <a href="javascript:;">Action </a>
                                                    </li>
                                                    <li>
                                                        <a href="javascript:;">Another action </a>
                                                    </li>
                                                    <li>
                                                        <a href="javascript:;">Something else here </a>
                                                    </li>
                                                    <li class="divider"> </li>
                                                    <li>
                                                        <a href="javascript:;">Separated link </a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                    <li data-date="20/04/2014">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Blue Chambray</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_1.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue">Rory Matthew</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">20 April 2014 : 10:45 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod eleifend ipsum, at posuere augue. Pellentesque mi felis, aliquam at iaculis eu, finibus eu ex. Integer efficitur leo eget dolor
                                                tincidunt, et dignissim risus lacinia. Nam in egestas nunc. Suspendisse potenti. Cras ullamcorper tincidunt malesuada. Sed sit amet molestie elit, vel placerat ipsum. Ut consectetur odio non
                                                est rhoncus volutpat. Nullam interdum, neque quis vehicula ornare, lacus elit dignissim purus, quis ultrices erat tortor eget felis. Cras commodo id massa at condimentum. Praesent dignissim luctus
                                                risus sed sodales.</p>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis
                                                qui ut. laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut. </p>
                                            <a href="javascript:;" class="btn btn-circle red">Read More</a>
                                        </div>
                                    </li>
                                    <li data-date="20/05/2014">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Timeline Received</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_2.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Andres Iniesta</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">20 May 2014 : 12:20 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod eleifend ipsum, at posuere augue. Pellentesque mi felis, aliquam at iaculis eu, finibus eu ex. Integer efficitur leo eget dolor
                                                tincidunt, et dignissim risus lacinia. Nam in egestas nunc. Suspendisse potenti. Cras ullamcorper tincidunt malesuada. Sed sit amet molestie elit, vel placerat ipsum. Ut consectetur odio non
                                                est rhoncus volutpat. Nullam interdum, neque quis vehicula ornare, lacus elit dignissim purus, quis ultrices erat tortor eget felis. Cras commodo id massa at condimentum. Praesent dignissim luctus
                                                risus sed sodales.</p>
                                            <a href="javascript:;" class="btn btn-circle green-turquoise">Read More</a>
                                        </div>
                                    </li>
                                    <li data-date="09/07/2014">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Event Success</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_1.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Matt Goldman</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">9 July 2014 : 8:15 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde.</p>
                                            <a href="javascript:;" class="btn btn-circle btn-outline purple-medium">View Summary</a>
                                            <div class="btn-group dropup pull-right">
                                                <button class="btn btn-circle green dropdown-toggle" type="button" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" aria-expanded="false"> Actions
                                                    <i class="fa fa-angle-down"></i>
                                                </button>
                                                <ul class="dropdown-menu pull-right" role="menu">
                                                    <li>
                                                        <a href="javascript:;">Action </a>
                                                    </li>
                                                    <li>
                                                        <a href="javascript:;">Another action </a>
                                                    </li>
                                                    <li>
                                                        <a href="javascript:;">Something else here </a>
                                                    </li>
                                                    <li class="divider"> </li>
                                                    <li>
                                                        <a href="javascript:;">Separated link </a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                    <li data-date="30/08/2014">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Conference Call</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_1.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Rory Matthew</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">30 August 2014 : 5:45 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <img class="timeline-body-img pull-left" src="../assets/pages/media/blog/5.jpg" alt="">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis
                                                qui ut. laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut. </p>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis
                                                qui ut. laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut. </p>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis
                                                qui ut. laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut. </p>
                                            <a href="javascript:;" class="btn btn-circle red">Read More</a>
                                        </div>
                                    </li>
                                    <li data-date="15/09/2014">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Conference Decision</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_5.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Jessica Wolf</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">15 September 2014 : 8:30 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <img class="timeline-body-img pull-right" src="../assets/pages/media/blog/6.jpg" alt="">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis
                                                qui ut.</p>
                                            <a href="javascript:;" class="btn btn-circle green-sharp">Read More</a>
                                        </div>
                                    </li>
                                    <li data-date="01/11/2014">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Timeline Received</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_2.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Andres Iniesta</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">1 November 2014 : 12:20 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod eleifend ipsum, at posuere augue. Pellentesque mi felis, aliquam at iaculis eu, finibus eu ex. Integer efficitur leo eget dolor
                                                tincidunt, et dignissim risus lacinia. Nam in egestas nunc. Suspendisse potenti. Cras ullamcorper tincidunt malesuada. Sed sit amet molestie elit, vel placerat ipsum. Ut consectetur odio non
                                                est rhoncus volutpat. Nullam interdum, neque quis vehicula ornare, lacus elit dignissim purus, quis ultrices erat tortor eget felis. Cras commodo id massa at condimentum. Praesent dignissim luctus
                                                risus sed sodales.</p>
                                            <a href="javascript:;" class="btn btn-circle green-turquoise">Read More</a>
                                        </div>
                                    </li>
                                    <li data-date="10/12/2014">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Timeline Received</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_2.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Andres Iniesta</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">10 December 2014 : 12:20 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod eleifend ipsum, at posuere augue. Pellentesque mi felis, aliquam at iaculis eu, finibus eu ex. Integer efficitur leo eget dolor
                                                tincidunt, et dignissim risus lacinia. Nam in egestas nunc. Suspendisse potenti. Cras ullamcorper tincidunt malesuada. Sed sit amet molestie elit, vel placerat ipsum. Ut consectetur odio non
                                                est rhoncus volutpat. Nullam interdum, neque quis vehicula ornare, lacus elit dignissim purus, quis ultrices erat tortor eget felis. Cras commodo id massa at condimentum. Praesent dignissim luctus
                                                risus sed sodales.</p>
                                            <a href="javascript:;" class="btn btn-circle green-turquoise">Read More</a>
                                        </div>
                                    </li>
                                    <li data-date="19/01/2015">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Timeline Received</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_2.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Andres Iniesta</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">19 January 2015 : 12:20 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod eleifend ipsum, at posuere augue. Pellentesque mi felis, aliquam at iaculis eu, finibus eu ex. Integer efficitur leo eget dolor
                                                tincidunt, et dignissim risus lacinia. Nam in egestas nunc. Suspendisse potenti. Cras ullamcorper tincidunt malesuada. Sed sit amet molestie elit, vel placerat ipsum. Ut consectetur odio non
                                                est rhoncus volutpat. Nullam interdum, neque quis vehicula ornare, lacus elit dignissim purus, quis ultrices erat tortor eget felis. Cras commodo id massa at condimentum. Praesent dignissim luctus
                                                risus sed sodales.</p>
                                            <a href="javascript:;" class="btn btn-circle green-turquoise">Read More</a>
                                        </div>
                                    </li>
                                    <li data-date="03/03/2015">
                                        <div class="mt-title">
                                            <h2 class="mt-content-title">Timeline Received</h2>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-avatar">
                                                <img src="../assets/pages/media/users/avatar80_2.jpg" />
                                            </div>
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">Andres Iniesta</a>
                                            </div>
                                            <div class="mt-author-datetime font-grey-mint">3 March 2015 : 12:20 PM</div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="mt-content border-grey-steel">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod eleifend ipsum, at posuere augue. Pellentesque mi felis, aliquam at iaculis eu, finibus eu ex. Integer efficitur leo eget dolor
                                                tincidunt, et dignissim risus lacinia. Nam in egestas nunc. Suspendisse potenti. Cras ullamcorper tincidunt malesuada. Sed sit amet molestie elit, vel placerat ipsum. Ut consectetur odio non
                                                est rhoncus volutpat. Nullam interdum, neque quis vehicula ornare, lacus elit dignissim purus, quis ultrices erat tortor eget felis. Cras commodo id massa at condimentum. Praesent dignissim luctus
                                                risus sed sodales.</p>
                                            <a href="javascript:;" class="btn btn-circle green-turquoise">Read More</a>
                                        </div>
                                    </li>
                                </ol>
                            </div>
                            <!-- .events-content -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-bubble font-dark hide"></i>
                            <span class="caption-subject font-hide bold uppercase">Recent Users</span>
                        </div>
                        <div class="actions">
                            <div class="btn-group">
                                <a class="btn green-haze btn-outline btn-circle btn-sm" href="javascript:;" data-toggle="dropdown" data-hover="dropdown" data-close-others="true"> Actions
                                    <i class="fa fa-angle-down"></i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li>
                                        <a href="javascript:;"> Option 1</a>
                                    </li>
                                    <li class="divider"> </li>
                                    <li>
                                        <a href="javascript:;">Option 2</a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">Option 3</a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">Option 4</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-4">
                                <!--begin: widget 1-1 -->
                                <div class="mt-widget-1">
                                    <div class="mt-icon">
                                        <a href="#">
                                            <i class="icon-plus"></i>
                                        </a>
                                    </div>
                                    <div class="mt-img">
                                        <img src="../assets/pages/media/users/avatar80_8.jpg"> </div>
                                    <div class="mt-body">
                                        <h3 class="mt-username">Diana Ellison</h3>
                                        <p class="mt-user-title"> Lorem Ipsum is simply dummy text. </p>
                                        <div class="mt-stats">
                                            <div class="btn-group btn-group btn-group-justified">
                                                <a href="javascript:;" class="btn font-red">
                                                    <i class="icon-bubbles"></i> 1,7k </a>
                                                <a href="javascript:;" class="btn font-green">
                                                    <i class="icon-social-twitter"></i> 2,6k </a>
                                                <a href="javascript:;" class="btn font-yellow">
                                                    <i class="icon-emoticon-smile"></i> 3,7k </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!--end: widget 1-1 -->
                            </div>
                            <div class="col-md-4">
                                <!--begin: widget 1-2 -->
                                <div class="mt-widget-1">
                                    <div class="mt-icon">
                                        <a href="#">
                                            <i class="icon-plus"></i>
                                        </a>
                                    </div>
                                    <div class="mt-img">
                                        <img src="../assets/pages/media/users/avatar80_7.jpg"> </div>
                                    <div class="mt-body">
                                        <h3 class="mt-username">Jason Baker</h3>
                                        <p class="mt-user-title"> Lorem Ipsum is simply dummy text. </p>
                                        <div class="mt-stats">
                                            <div class="btn-group btn-group btn-group-justified">
                                                <a href="javascript:;" class="btn font-yellow">
                                                    <i class="icon-bubbles"></i> 1,7k </a>
                                                <a href="javascript:;" class="btn font-blue">
                                                    <i class="icon-social-twitter"></i> 2,6k </a>
                                                <a href="javascript:;" class="btn font-green">
                                                    <i class="icon-emoticon-smile"></i> 3,7k </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!--end: widget 1-2 -->
                            </div>
                            <div class="col-md-4">
                                <!--begin: widget 1-3 -->
                                <div class="mt-widget-1">
                                    <div class="mt-icon">
                                        <a href="#">
                                            <i class="icon-plus"></i>
                                        </a>
                                    </div>
                                    <div class="mt-img">
                                        <img src="../assets/pages/media/users/avatar80_6.jpg"> </div>
                                    <div class="mt-body">
                                        <h3 class="mt-username">Julia Berry</h3>
                                        <p class="mt-user-title"> Lorem Ipsum is simply dummy text. </p>
                                        <div class="mt-stats">
                                            <div class="btn-group btn-group btn-group-justified">
                                                <a href="javascript:;" class="btn font-yellow">
                                                    <i class="icon-bubbles"></i> 1,7k </a>
                                                <a href="javascript:;" class="btn font-red">
                                                    <i class="icon-social-twitter"></i> 2,6k </a>
                                                <a href="javascript:;" class="btn font-green">
                                                    <i class="icon-emoticon-smile"></i> 3,7k </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!--end: widget 1-3 -->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="portlet light portlet-fit bordered">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-microphone font-dark hide"></i>
                            <span class="caption-subject bold font-dark uppercase"> Recent Works</span>
                            <span class="caption-helper">default option...</span>
                        </div>
                        <div class="actions">
                            <div class="btn-group btn-group-devided" data-toggle="buttons">
                                <label class="btn red btn-outline btn-circle btn-sm active">
                                    <input type="radio" name="options" class="toggle" id="option1">Settings</label>
                                <label class="btn  red btn-outline btn-circle btn-sm">
                                    <input type="radio" name="options" class="toggle" id="option2">Tools</label>
                            </div>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="mt-widget-2">
                                    <div class="mt-head" style="background-image: url(../assets/pages/img/background/32.jpg);">
                                        <div class="mt-head-label">
                                            <button type="button" class="btn btn-success">Manhattan</button>
                                        </div>
                                        <div class="mt-head-user">
                                            <div class="mt-head-user-img">
                                                <img src="../assets/pages/img/avatars/team7.jpg"> </div>
                                            <div class="mt-head-user-info">
                                                <span class="mt-user-name">Chris Jagers</span>
                                                <span class="mt-user-time">
                                                    <i class="icon-emoticon-smile"></i> 3 mins ago </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="mt-body">
                                        <h3 class="mt-body-title"> Thomas Clark </h3>
                                        <p class="mt-body-description"> It is a long established fact that a reader will be distracted </p>
                                        <ul class="mt-body-stats">
                                            <li class="font-green">
                                                <i class="icon-emoticon-smile"></i> 3,7k</li>
                                            <li class="font-yellow">
                                                <i class=" icon-social-twitter"></i> 3,7k</li>
                                            <li class="font-red">
                                                <i class="  icon-bubbles"></i> 3,7k</li>
                                        </ul>
                                        <div class="mt-body-actions">
                                            <div class="btn-group btn-group btn-group-justified">
                                                <a href="javascript:;" class="btn">
                                                    <i class="icon-bubbles"></i> Bookmark </a>
                                                <a href="javascript:;" class="btn ">
                                                    <i class="icon-social-twitter"></i> Share </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="mt-widget-2">
                                    <div class="mt-head" style="background-image: url(../assets/pages/img/background/43.jpg);">
                                        <div class="mt-head-label">
                                            <button type="button" class="btn btn-danger">London</button>
                                        </div>
                                        <div class="mt-head-user">
                                            <div class="mt-head-user-img">
                                                <img src="../assets/pages/img/avatars/team3.jpg"> </div>
                                            <div class="mt-head-user-info">
                                                <span class="mt-user-name">Harry Harris</span>
                                                <span class="mt-user-time">
                                                    <i class="icon-user"></i> 3 mins ago </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="mt-body">
                                        <h3 class="mt-body-title"> Christian Davidson </h3>
                                        <p class="mt-body-description"> It is a long established fact that a reader will be distracted </p>
                                        <ul class="mt-body-stats">
                                            <li class="font-green">
                                                <i class="icon-emoticon-smile"></i> 3,7k</li>
                                            <li class="font-yellow">
                                                <i class=" icon-social-twitter"></i> 3,7k</li>
                                            <li class="font-red">
                                                <i class="  icon-bubbles"></i> 3,7k</li>
                                        </ul>
                                        <div class="mt-body-actions">
                                            <div class="btn-group btn-group btn-group-justified">
                                                <a href="javascript:;" class="btn ">
                                                    <i class="icon-bubbles"></i> Bookmark </a>
                                                <a href="javascript:;" class="btn ">
                                                    <i class="icon-social-twitter"></i> Share </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-6">
                <div class="portlet light portlet-fit bordered">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-microphone font-dark hide"></i>
                            <span class="caption-subject bold font-dark uppercase"> Recent Projects</span>
                            <span class="caption-helper">default option...</span>
                        </div>
                        <div class="actions">
                            <div class="btn-group btn-group-devided" data-toggle="buttons">
                                <label class="btn blue btn-outline btn-circle btn-sm active">
                                    <input type="radio" name="options" class="toggle" id="option1">Actions</label>
                                <label class="btn  blue btn-outline btn-circle btn-sm">
                                    <input type="radio" name="options" class="toggle" id="option2">Tools</label>
                            </div>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="mt-widget-4">
                                    <div class="mt-img-container">
                                        <img src="../assets/pages/img/background/34.jpg" /> </div>
                                    <div class="mt-container bg-purple-opacity">
                                        <div class="mt-head-title"> Website Revamp & Deployment </div>
                                        <div class="mt-body-icons">
                                            <a href="#">
                                                <i class=" icon-pencil"></i>
                                            </a>
                                            <a href="#">
                                                <i class=" icon-map"></i>
                                            </a>
                                            <a href="#">
                                                <i class=" icon-trash"></i>
                                            </a>
                                        </div>
                                        <div class="mt-footer-button">
                                            <button type="button" class="btn btn-circle btn-danger btn-sm">Dior</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="mt-widget-4">
                                    <div class="mt-img-container">
                                        <img src="../assets/pages/img/background/46.jpg" /> </div>
                                    <div class="mt-container bg-green-opacity">
                                        <div class="mt-head-title"> CRM Development & Deployment </div>
                                        <div class="mt-body-icons">
                                            <a href="#">
                                                <i class=" icon-social-twitter"></i>
                                            </a>
                                            <a href="#">
                                                <i class=" icon-bubbles"></i>
                                            </a>
                                            <a href="#">
                                                <i class=" icon-bell"></i>
                                            </a>
                                        </div>
                                        <div class="mt-footer-button">
                                            <button type="button" class="btn btn-circle blue-ebonyclay btn-sm">Nike</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="mt-widget-4">
                                    <div class="mt-img-container">
                                        <img src="../assets/pages/img/background/37.jpg" /> </div>
                                    <div class="mt-container bg-dark-opacity">
                                        <div class="mt-head-title"> Marketing Campaigns </div>
                                        <div class="mt-body-icons">
                                            <a href="#">
                                                <i class=" icon-bubbles"></i>
                                            </a>
                                            <a href="#">
                                                <i class=" icon-map"></i>
                                            </a>
                                            <a href="#">
                                                <i class=" icon-cup"></i>
                                            </a>
                                        </div>
                                        <div class="mt-footer-button">
                                            <button type="button" class="btn btn-circle btn-success btn-sm">Honda</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="portlet light portlet-fit bordered">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-microphone font-dark hide"></i>
                            <span class="caption-subject bold font-dark uppercase"> Activities</span>
                            <span class="caption-helper">default option...</span>
                        </div>
                        <div class="actions">
                            <div class="btn-group">
                                <a class="btn red btn-outline btn-circle btn-sm" href="javascript:;" data-toggle="dropdown" data-hover="dropdown" data-close-others="true"> Actions
                                    <i class="fa fa-angle-down"></i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li>
                                        <a href="javascript:;"> Option 1</a>
                                    </li>
                                    <li class="divider"> </li>
                                    <li>
                                        <a href="javascript:;">Option 2</a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">Option 3</a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">Option 4</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="mt-widget-3">
                                    <div class="mt-head bg-blue-hoki">
                                        <div class="mt-head-icon">
                                            <i class=" icon-social-twitter"></i>
                                        </div>
                                        <div class="mt-head-desc"> Lorem Ipsum is simply dummy text of the ... </div>
                                        <span class="mt-head-date"> 25 Jan, 2015 </span>
                                        <div class="mt-head-button">
                                            <button type="button" class="btn btn-circle btn-outline white btn-sm">Add</button>
                                        </div>
                                    </div>
                                    <div class="mt-body-actions-icons">
                                        <div class="btn-group btn-group btn-group-justified">
                                            <a href="javascript:;" class="btn ">
                                                <span class="mt-icon">
                                                    <i class="glyphicon glyphicon-align-justify"></i>
                                                </span>RECORD </a>
                                            <a href="javascript:;" class="btn ">
                                                <span class="mt-icon">
                                                    <i class="glyphicon glyphicon-camera"></i>
                                                </span>PHOTO </a>
                                            <a href="javascript:;" class="btn ">
                                                <span class="mt-icon">
                                                    <i class="glyphicon glyphicon-calendar"></i>
                                                </span>DATE </a>
                                            <a href="javascript:;" class="btn ">
                                                <span class="mt-icon">
                                                    <i class="glyphicon glyphicon-record"></i>
                                                </span>RANC </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="mt-widget-3">
                                    <div class="mt-head bg-red">
                                        <div class="mt-head-icon">
                                            <i class="icon-user"></i>
                                        </div>
                                        <div class="mt-head-desc"> Lorem Ipsum is simply dummy text of the ... </div>
                                        <span class="mt-head-date"> 12 Feb, 2016 </span>
                                        <div class="mt-head-button">
                                            <button type="button" class="btn btn-circle btn-outline white btn-sm">Add</button>
                                        </div>
                                    </div>
                                    <div class="mt-body-actions-icons">
                                        <div class="btn-group btn-group btn-group-justified">
                                            <a href="javascript:;" class="btn ">
                                                <span class="mt-icon">
                                                    <i class="glyphicon glyphicon-align-justify"></i>
                                                </span>RECORD </a>
                                            <a href="javascript:;" class="btn ">
                                                <span class="mt-icon">
                                                    <i class="glyphicon glyphicon-camera"></i>
                                                </span>PHOTO </a>
                                            <a href="javascript:;" class="btn ">
                                                <span class="mt-icon">
                                                    <i class="glyphicon glyphicon-calendar"></i>
                                                </span>DATE </a>
                                            <a href="javascript:;" class="btn ">
                                                <span class="mt-icon">
                                                    <i class="glyphicon glyphicon-record"></i>
                                                </span>RANC </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="mt-widget-3">
                                    <div class="mt-head bg-green">
                                        <div class="mt-head-icon">
                                            <i class=" icon-graduation"></i>
                                        </div>
                                        <div class="mt-head-desc"> Lorem Ipsum is simply dummy text of the ... </div>
                                        <span class="mt-head-date"> 3 Mar, 2015 </span>
                                        <div class="mt-head-button">
                                            <button type="button" class="btn btn-circle btn-outline white btn-sm">Add</button>
                                        </div>
                                    </div>
                                    <div class="mt-body-actions-icons">
                                        <div class="btn-group btn-group btn-group-justified">
                                            <a href="javascript:;" class="btn ">
                                                <span class="mt-icon">
                                                    <i class="glyphicon glyphicon-align-justify"></i>
                                                </span>RECORD </a>
                                            <a href="javascript:;" class="btn ">
                                                <span class="mt-icon">
                                                    <i class="glyphicon glyphicon-camera"></i>
                                                </span>PHOTO </a>
                                            <a href="javascript:;" class="btn ">
                                                <span class="mt-icon">
                                                    <i class="glyphicon glyphicon-calendar"></i>
                                                </span>DATE </a>
                                            <a href="javascript:;" class="btn ">
                                                <span class="mt-icon">
                                                    <i class="glyphicon glyphicon-record"></i>
                                                </span>RANC </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END PAGE BASE CONTENT -->
    </div>
    <!-- END CONTENT BODY -->
</div>
<!-- END CONTENT -->
